# Redis - cache and message queue
redis:
  # name of the Redis Docker container
  host:
  port:

# Triple store
tripleStore:
  # full SPARQL read endpoint URL
  endpointUrl:
  # full SPARQL update endpoint URL
  updateUrl:
  user:
  password:
