# Web app URL
webUrl:

# Rate limiting
throttler:
  # time-to-live (TTL) in seconds that each request will last in storage (0 = infinite)
  ttl:
  # max. amount of requests client can make in given TTL
  limit:
