# Redis - message queue
redis:
  # name of the Redis Docker container
  host:
  port:

# Ticketmaster for developers: https://developer.ticketmaster.com/
ticketmaster:
  # base URL for the Ticketmaster Discovery API: https://developer.ticketmaster.com/products-and-docs/apis/discovery-api/v2/
  url:
  # get your API key here: https://developer-acct.ticketmaster.com/user/login
  apiKey:

# GoOut
goout:
  # base URL of the GoOut - cs/en localization supported
  url:

# Ticketportal
ticketportal:
  # base URL of the Ticketportal music page
  url:
